export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Relationships = never[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          nmls_id: string | null;
          phone: string | null;
          subscription_tier: "trial" | "starter" | "pro" | "team";
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          trial_ends_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          nmls_id?: string | null;
          phone?: string | null;
          subscription_tier?: "trial" | "starter" | "pro" | "team";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          nmls_id?: string | null;
          phone?: string | null;
          subscription_tier?: "trial" | "starter" | "pro" | "team";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      contacts: {
        Row: {
          id: string;
          user_id: string;
          type: "borrower" | "realtor" | "title" | "other";
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          property_value: number | null;
          loan_balance: number | null;
          note_rate: number | null;
          loan_close_date: string | null;
          last_contact_at: string | null;
          pulse_active: boolean | null;
          pulse_paused: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "borrower" | "realtor" | "title" | "other";
          first_name: string;
          last_name: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          property_value?: number | null;
          loan_balance?: number | null;
          note_rate?: number | null;
          loan_close_date?: string | null;
          last_contact_at?: string | null;
          pulse_active?: boolean | null;
          pulse_paused?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: "borrower" | "realtor" | "title" | "other";
          first_name?: string;
          last_name?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          property_value?: number | null;
          loan_balance?: number | null;
          note_rate?: number | null;
          loan_close_date?: string | null;
          last_contact_at?: string | null;
          pulse_active?: boolean | null;
          pulse_paused?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      lenders: {
        Row: {
          id: string;
          name: string;
          type: "wholesale" | "retail" | "portfolio" | "hard_money" | null;
          is_system: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: "wholesale" | "retail" | "portfolio" | "hard_money" | null;
          is_system?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: "wholesale" | "retail" | "portfolio" | "hard_money" | null;
          is_system?: boolean | null;
          created_at?: string;
        };
        Relationships: Relationships;
      };
      loan_files: {
        Row: {
          id: string;
          user_id: string;
          borrower_id: string | null;
          lender_id: string | null;
          file_number: string | null;
          loan_type: "purchase" | "refinance" | "heloc" | "non_qm" | "va" | "fha" | "usda";
          loan_purpose: "primary_residence" | "second_home" | "investment" | null;
          loan_amount: number | null;
          property_address: string | null;
          property_city: string | null;
          property_state: string | null;
          property_zip: string | null;
          estimated_value: number | null;
          status: "intake" | "verification" | "submitted" | "in_underwriting" | "conditional_approval" | "clear_to_close" | "closed" | "withdrawn";
          submission_readiness_score: number | null;
          readiness_breakdown: Json | null;
          rate_lock_date: string | null;
          rate_lock_expires_at: string | null;
          closing_date: string | null;
          portal_token: string | null;
          portal_expires_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          borrower_id?: string | null;
          lender_id?: string | null;
          file_number?: string | null;
          loan_type: "purchase" | "refinance" | "heloc" | "non_qm" | "va" | "fha" | "usda";
          loan_purpose?: "primary_residence" | "second_home" | "investment" | null;
          loan_amount?: number | null;
          property_address?: string | null;
          property_city?: string | null;
          property_state?: string | null;
          property_zip?: string | null;
          estimated_value?: number | null;
          status?: "intake" | "verification" | "submitted" | "in_underwriting" | "conditional_approval" | "clear_to_close" | "closed" | "withdrawn";
          submission_readiness_score?: number | null;
          readiness_breakdown?: Json | null;
          rate_lock_date?: string | null;
          rate_lock_expires_at?: string | null;
          closing_date?: string | null;
          portal_token?: string | null;
          portal_expires_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          borrower_id?: string | null;
          lender_id?: string | null;
          file_number?: string | null;
          loan_type?: "purchase" | "refinance" | "heloc" | "non_qm" | "va" | "fha" | "usda";
          loan_purpose?: "primary_residence" | "second_home" | "investment" | null;
          loan_amount?: number | null;
          property_address?: string | null;
          property_city?: string | null;
          property_state?: string | null;
          property_zip?: string | null;
          estimated_value?: number | null;
          status?: "intake" | "verification" | "submitted" | "in_underwriting" | "conditional_approval" | "clear_to_close" | "closed" | "withdrawn";
          submission_readiness_score?: number | null;
          readiness_breakdown?: Json | null;
          rate_lock_date?: string | null;
          rate_lock_expires_at?: string | null;
          closing_date?: string | null;
          portal_token?: string | null;
          portal_expires_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      documents: {
        Row: {
          id: string;
          loan_file_id: string;
          type: "w2" | "pay_stub" | "bank_statement" | "tax_return_1040" | "schedule_c" | "schedule_e" | "purchase_contract" | "mortgage_statement" | "drivers_license" | "social_security" | "gift_letter" | "voe" | "appraisal" | "title_report" | "homeowners_insurance" | "hoa_statement" | "rental_agreement" | "conditional_approval" | "other";
          status: "pending" | "uploaded" | "processing" | "verified" | "needs_attention" | "rejected" | "expired";
          file_path: string | null;
          original_filename: string | null;
          file_size_bytes: number | null;
          mime_type: string | null;
          extracted_data: Json | null;
          extraction_confidence: number | null;
          verification_flags: Json | null;
          required: boolean | null;
          notes: string | null;
          uploaded_at: string | null;
          verified_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id: string;
          type: "w2" | "pay_stub" | "bank_statement" | "tax_return_1040" | "schedule_c" | "schedule_e" | "purchase_contract" | "mortgage_statement" | "drivers_license" | "social_security" | "gift_letter" | "voe" | "appraisal" | "title_report" | "homeowners_insurance" | "hoa_statement" | "rental_agreement" | "conditional_approval" | "other";
          status?: "pending" | "uploaded" | "processing" | "verified" | "needs_attention" | "rejected" | "expired";
          file_path?: string | null;
          original_filename?: string | null;
          file_size_bytes?: number | null;
          mime_type?: string | null;
          extracted_data?: Json | null;
          extraction_confidence?: number | null;
          verification_flags?: Json | null;
          required?: boolean | null;
          notes?: string | null;
          uploaded_at?: string | null;
          verified_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string;
          type?: "w2" | "pay_stub" | "bank_statement" | "tax_return_1040" | "schedule_c" | "schedule_e" | "purchase_contract" | "mortgage_statement" | "drivers_license" | "social_security" | "gift_letter" | "voe" | "appraisal" | "title_report" | "homeowners_insurance" | "hoa_statement" | "rental_agreement" | "conditional_approval" | "other";
          status?: "pending" | "uploaded" | "processing" | "verified" | "needs_attention" | "rejected" | "expired";
          file_path?: string | null;
          original_filename?: string | null;
          file_size_bytes?: number | null;
          mime_type?: string | null;
          extracted_data?: Json | null;
          extraction_confidence?: number | null;
          verification_flags?: Json | null;
          required?: boolean | null;
          notes?: string | null;
          uploaded_at?: string | null;
          verified_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      conditions: {
        Row: {
          id: string;
          loan_file_id: string;
          source: "lender" | "internal" | "title" | "appraisal";
          lender_condition_text: string | null;
          plain_english_summary: string | null;
          required_document_type: string | null;
          status: "open" | "borrower_notified" | "document_received" | "validated" | "submitted_to_lender" | "cleared" | "waived";
          priority: "high" | "normal" | "low" | null;
          due_date: string | null;
          document_id: string | null;
          borrower_task_sent_at: string | null;
          validated_at: string | null;
          cleared_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id: string;
          source: "lender" | "internal" | "title" | "appraisal";
          lender_condition_text?: string | null;
          plain_english_summary?: string | null;
          required_document_type?: string | null;
          status?: "open" | "borrower_notified" | "document_received" | "validated" | "submitted_to_lender" | "cleared" | "waived";
          priority?: "high" | "normal" | "low" | null;
          due_date?: string | null;
          document_id?: string | null;
          borrower_task_sent_at?: string | null;
          validated_at?: string | null;
          cleared_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string;
          source?: "lender" | "internal" | "title" | "appraisal";
          lender_condition_text?: string | null;
          plain_english_summary?: string | null;
          required_document_type?: string | null;
          status?: "open" | "borrower_notified" | "document_received" | "validated" | "submitted_to_lender" | "cleared" | "waived";
          priority?: "high" | "normal" | "low" | null;
          due_date?: string | null;
          document_id?: string | null;
          borrower_task_sent_at?: string | null;
          validated_at?: string | null;
          cleared_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      messages: {
        Row: {
          id: string;
          loan_file_id: string | null;
          contact_id: string | null;
          user_id: string;
          channel: "sms" | "email" | "in_app";
          direction: "outbound" | "inbound";
          recipient_type: "borrower" | "realtor" | "title" | "lo" | null;
          recipient_email: string | null;
          recipient_phone: string | null;
          subject: string | null;
          content: string;
          status: "draft" | "approved" | "sending" | "sent" | "delivered" | "failed" | null;
          trigger_type: string | null;
          external_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id?: string | null;
          contact_id?: string | null;
          user_id: string;
          channel: "sms" | "email" | "in_app";
          direction?: "outbound" | "inbound";
          recipient_type?: "borrower" | "realtor" | "title" | "lo" | null;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          subject?: string | null;
          content: string;
          status?: "draft" | "approved" | "sending" | "sent" | "delivered" | "failed" | null;
          trigger_type?: string | null;
          external_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string | null;
          contact_id?: string | null;
          user_id?: string;
          channel?: "sms" | "email" | "in_app";
          direction?: "outbound" | "inbound";
          recipient_type?: "borrower" | "realtor" | "title" | "lo" | null;
          recipient_email?: string | null;
          recipient_phone?: string | null;
          subject?: string | null;
          content?: string;
          status?: "draft" | "approved" | "sending" | "sent" | "delivered" | "failed" | null;
          trigger_type?: string | null;
          external_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
        };
        Relationships: Relationships;
      };
      lender_submissions: {
        Row: {
          id: string;
          loan_file_id: string;
          lender_id: string;
          submitted_by: string;
          submission_type: "initial" | "conditions" | "resubmission" | null;
          status: "preparing" | "submitted" | "acknowledged" | "conditions_issued" | "cleared" | null;
          lender_loan_number: string | null;
          documents_included: Json | null;
          notes: string | null;
          submitted_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id: string;
          lender_id: string;
          submitted_by: string;
          submission_type?: "initial" | "conditions" | "resubmission" | null;
          status?: "preparing" | "submitted" | "acknowledged" | "conditions_issued" | "cleared" | null;
          lender_loan_number?: string | null;
          documents_included?: Json | null;
          notes?: string | null;
          submitted_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string;
          lender_id?: string;
          submitted_by?: string;
          submission_type?: "initial" | "conditions" | "resubmission" | null;
          status?: "preparing" | "submitted" | "acknowledged" | "conditions_issued" | "cleared" | null;
          lender_loan_number?: string | null;
          documents_included?: Json | null;
          notes?: string | null;
          submitted_at?: string | null;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      pulse_events: {
        Row: {
          id: string;
          contact_id: string;
          user_id: string;
          event_type: "rate_drop" | "equity_trigger" | "loan_anniversary" | "listing_activity" | "manual";
          event_data: Json | null;
          reasoning: string | null;
          action_taken: "nudge_sent" | "dismissed" | "snoozed" | "pending" | null;
          message_id: string | null;
          detected_at: string | null;
          actioned_at: string | null;
        };
        Insert: {
          id?: string;
          contact_id: string;
          user_id: string;
          event_type: "rate_drop" | "equity_trigger" | "loan_anniversary" | "listing_activity" | "manual";
          event_data?: Json | null;
          reasoning?: string | null;
          action_taken?: "nudge_sent" | "dismissed" | "snoozed" | "pending" | null;
          message_id?: string | null;
          detected_at?: string | null;
          actioned_at?: string | null;
        };
        Update: {
          id?: string;
          contact_id?: string;
          user_id?: string;
          event_type?: "rate_drop" | "equity_trigger" | "loan_anniversary" | "listing_activity" | "manual";
          event_data?: Json | null;
          reasoning?: string | null;
          action_taken?: "nudge_sent" | "dismissed" | "snoozed" | "pending" | null;
          message_id?: string | null;
          detected_at?: string | null;
          actioned_at?: string | null;
        };
        Relationships: Relationships;
      };
      token_usage: {
        Row: {
          id: string;
          user_id: string;
          loan_file_id: string | null;
          module: string;
          model: string;
          input_tokens: number;
          output_tokens: number;
          cost_usd: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          loan_file_id?: string | null;
          module: string;
          model: string;
          input_tokens: number;
          output_tokens: number;
          cost_usd: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          loan_file_id?: string | null;
          module?: string;
          model?: string;
          input_tokens?: number;
          output_tokens?: number;
          cost_usd?: number;
          created_at?: string;
        };
        Relationships: Relationships;
      };
      loan_applications: {
        Row: {
          id: string;
          loan_file_id: string;
          borrower_first_name: string | null;
          borrower_last_name: string | null;
          borrower_ssn_last4: string | null;
          borrower_dob: string | null;
          borrower_email: string | null;
          borrower_phone: string | null;
          borrower_marital_status: "married" | "separated" | "unmarried" | null;
          borrower_dependents: number | null;
          borrower_citizenship: "us_citizen" | "permanent_resident" | "non_permanent_resident" | null;
          current_address: string | null;
          current_city: string | null;
          current_state: string | null;
          current_zip: string | null;
          current_housing: "own" | "rent" | "living_rent_free" | null;
          years_at_address: number | null;
          employer_name: string | null;
          employer_address: string | null;
          employer_phone: string | null;
          employment_start_date: string | null;
          years_employed: number | null;
          job_title: string | null;
          self_employed: boolean | null;
          base_income: number | null;
          overtime_income: number | null;
          bonus_income: number | null;
          commission_income: number | null;
          other_income: number | null;
          checking_balance: number | null;
          savings_balance: number | null;
          retirement_balance: number | null;
          other_assets: Json | null;
          liabilities: Json | null;
          outstanding_judgments: boolean | null;
          declared_bankruptcy: boolean | null;
          property_foreclosed: boolean | null;
          party_to_lawsuit: boolean | null;
          loan_obligations: boolean | null;
          delinquent_federal_debt: boolean | null;
          co_maker_note: boolean | null;
          intend_to_occupy: boolean | null;
          ownership_interest: boolean | null;
          co_borrower: Json | null;
          completed_sections: string[] | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id: string;
          borrower_first_name?: string | null;
          borrower_last_name?: string | null;
          borrower_ssn_last4?: string | null;
          borrower_dob?: string | null;
          borrower_email?: string | null;
          borrower_phone?: string | null;
          borrower_marital_status?: "married" | "separated" | "unmarried" | null;
          borrower_dependents?: number | null;
          borrower_citizenship?: "us_citizen" | "permanent_resident" | "non_permanent_resident" | null;
          current_address?: string | null;
          current_city?: string | null;
          current_state?: string | null;
          current_zip?: string | null;
          current_housing?: "own" | "rent" | "living_rent_free" | null;
          years_at_address?: number | null;
          employer_name?: string | null;
          employer_address?: string | null;
          employer_phone?: string | null;
          employment_start_date?: string | null;
          years_employed?: number | null;
          job_title?: string | null;
          self_employed?: boolean | null;
          base_income?: number | null;
          overtime_income?: number | null;
          bonus_income?: number | null;
          commission_income?: number | null;
          other_income?: number | null;
          checking_balance?: number | null;
          savings_balance?: number | null;
          retirement_balance?: number | null;
          other_assets?: Json | null;
          liabilities?: Json | null;
          outstanding_judgments?: boolean | null;
          declared_bankruptcy?: boolean | null;
          property_foreclosed?: boolean | null;
          party_to_lawsuit?: boolean | null;
          loan_obligations?: boolean | null;
          delinquent_federal_debt?: boolean | null;
          co_maker_note?: boolean | null;
          intend_to_occupy?: boolean | null;
          ownership_interest?: boolean | null;
          co_borrower?: Json | null;
          completed_sections?: string[] | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string;
          borrower_first_name?: string | null;
          borrower_last_name?: string | null;
          borrower_ssn_last4?: string | null;
          borrower_dob?: string | null;
          borrower_email?: string | null;
          borrower_phone?: string | null;
          borrower_marital_status?: "married" | "separated" | "unmarried" | null;
          borrower_dependents?: number | null;
          borrower_citizenship?: "us_citizen" | "permanent_resident" | "non_permanent_resident" | null;
          current_address?: string | null;
          current_city?: string | null;
          current_state?: string | null;
          current_zip?: string | null;
          current_housing?: "own" | "rent" | "living_rent_free" | null;
          years_at_address?: number | null;
          employer_name?: string | null;
          employer_address?: string | null;
          employer_phone?: string | null;
          employment_start_date?: string | null;
          years_employed?: number | null;
          job_title?: string | null;
          self_employed?: boolean | null;
          base_income?: number | null;
          overtime_income?: number | null;
          bonus_income?: number | null;
          commission_income?: number | null;
          other_income?: number | null;
          checking_balance?: number | null;
          savings_balance?: number | null;
          retirement_balance?: number | null;
          other_assets?: Json | null;
          liabilities?: Json | null;
          outstanding_judgments?: boolean | null;
          declared_bankruptcy?: boolean | null;
          property_foreclosed?: boolean | null;
          party_to_lawsuit?: boolean | null;
          loan_obligations?: boolean | null;
          delinquent_federal_debt?: boolean | null;
          co_maker_note?: boolean | null;
          intend_to_occupy?: boolean | null;
          ownership_interest?: boolean | null;
          co_borrower?: Json | null;
          completed_sections?: string[] | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      rate_sheets: {
        Row: {
          id: string;
          user_id: string;
          lender_id: string | null;
          lender_name: string;
          effective_date: string | null;
          expires_at: string | null;
          file_path: string | null;
          original_filename: string | null;
          status: "processing" | "parsed" | "failed" | "active" | "superseded";
          parsed_rates: Json | null;
          parse_error: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lender_id?: string | null;
          lender_name: string;
          effective_date?: string | null;
          expires_at?: string | null;
          file_path?: string | null;
          original_filename?: string | null;
          status?: "processing" | "parsed" | "failed" | "active" | "superseded";
          parsed_rates?: Json | null;
          parse_error?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lender_id?: string | null;
          lender_name?: string;
          effective_date?: string | null;
          expires_at?: string | null;
          file_path?: string | null;
          original_filename?: string | null;
          status?: "processing" | "parsed" | "failed" | "active" | "superseded";
          parsed_rates?: Json | null;
          parse_error?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
      disclosures: {
        Row: {
          id: string;
          loan_file_id: string;
          disclosure_type: "loan_estimate" | "closing_disclosure" | "intent_to_proceed" | "right_to_cancel" | "anti_steering" | "affiliated_business" | "servicing" | "arm_disclosure" | "initial_escrow" | "homeowners_insurance";
          stage: "initial" | "revised" | "final";
          status: "pending" | "sent" | "viewed" | "signed" | "waived";
          sent_at: string | null;
          viewed_at: string | null;
          signed_at: string | null;
          waived_at: string | null;
          due_date: string | null;
          method: "email" | "in_person" | "mail" | "electronic" | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          loan_file_id: string;
          disclosure_type: "loan_estimate" | "closing_disclosure" | "intent_to_proceed" | "right_to_cancel" | "anti_steering" | "affiliated_business" | "servicing" | "arm_disclosure" | "initial_escrow" | "homeowners_insurance";
          stage?: "initial" | "revised" | "final";
          status?: "pending" | "sent" | "viewed" | "signed" | "waived";
          sent_at?: string | null;
          viewed_at?: string | null;
          signed_at?: string | null;
          waived_at?: string | null;
          due_date?: string | null;
          method?: "email" | "in_person" | "mail" | "electronic" | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          loan_file_id?: string;
          disclosure_type?: "loan_estimate" | "closing_disclosure" | "intent_to_proceed" | "right_to_cancel" | "anti_steering" | "affiliated_business" | "servicing" | "arm_disclosure" | "initial_escrow" | "homeowners_insurance";
          stage?: "initial" | "revised" | "final";
          status?: "pending" | "sent" | "viewed" | "signed" | "waived";
          sent_at?: string | null;
          viewed_at?: string | null;
          signed_at?: string | null;
          waived_at?: string | null;
          due_date?: string | null;
          method?: "email" | "in_person" | "mail" | "electronic" | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: Relationships;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
